export { default as validateFormCatalog } from './catalog';
export { default as validateFormCatalogModal } from './catalog-modal';
export { default as validateFormBiologist } from './biologist';
export { default as validateFormCostCare } from './cost-care';
export { default as validateFormCostCommercial } from './cost-commercial';
export { default as validateFormCostProduct } from './cost-product';
export { default as validateFormQuestions } from './questions';
export { default as validateFormQuiz1 } from './quiz-1';
export { default as validateFormQuiz2 } from './quiz-2';
